In [2]:
#Importar as bibliotecas
from numpy import pi 
from numpy import sys
import numpy as np

In [3]:
print('Versão atual do numpy', np.__version__)

Versão atual do numpy 1.18.5


In [10]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a

array([20, 30, 40, 50])

In [11]:
b

array([0, 1, 2, 3])

In [12]:
#Caclulo aritmético de subtração
c = a - b
c

array([20, 29, 38, 47])

In [13]:
#Exponenciação do Array de b
b**2

array([0, 1, 4, 9], dtype=int32)

In [14]:
#Multiplicando array pelo seno de a
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [15]:
#Operador relacional 
a < 35

array([ True,  True, False, False])

In [16]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A*B

array([[2, 0],
       [0, 4]])

In [17]:
#Multiplicação do produto da matriz
A @ B

array([[5, 4],
       [3, 4]])

In [18]:
#Outra forma de multiplicação do produto da matriz
A.dot(B)

array([[5, 4],
       [3, 4]])

In [20]:
#Criando instancia de gerador de numeros aleatorios padrão
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [21]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])